" Leader
let mapleader=","

" Misc. config
set nocompatible
set encoding=utf-8
set backspace=indent,eol,start  " Why would I ever want backspace to not work?
set scrolloff=3                 " Start scrolling 3 lines before edge
set showmatch                   " Highlight matching brackets on entry
set laststatus=2                " Always show status line
set autoread                    " Sensibly read changed files
set showcmd                     " Display incomplete commands
set noswapfile                  " No swap files
set rtp+=/usr/local/opt/fzf     " FZF config
" let &colorcolumn="80"         " Highlight column 80
autocmd InsertEnter,InsertLeave * set cul! " Toggle cursorline in insert mode.
set clipboard=unnamed

set wildignore+=*/.git/*,*/.hg/*,*/.svn/*        " Linux/MacOSX

" Indentation
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
filetype indent on
set foldmethod=indent                      " Fold based on source indentation
set foldlevelstart=99                      " Expand all folds by default
autocmd BufWritePre * StripWhitespace

" Searching
set incsearch
set hlsearch
set smartcase
set ignorecase

" Line numbering & formatting
set number
set nuw=6
set relativenumber
set cursorline
set ruler
set wrap
set linebreak
set wildmenu
set lazyredraw
set showmatch



" Colors
set t_Co=256
syntax enable

set background=dark
" F5 toggles background dark/light
" call togglebg#map("<F5>")

set cursorline                  " Where am I?
set noshowmode " lightline shows the status not vim
set undolevels=5000
set scrolloff=999
set laststatus=2
" hi CursorLine term=bold cterm=bold

" Folding {{{
set foldenable
set foldlevelstart=10
set foldnestmax=10
" }}}

set nobackup
set nowritebackup
set noswapfile
set hidden
set history=100
set path+=**
set nolist
set splitbelow
set splitright

set diffopt=vertical
set updatetime=300

set completeopt=menu,menuone,preview,noselect,noinsert
if executable('ag')
    " Note we extract the column as well as the file and line number
    set grepprg=ag\ --nogroup\ --nocolor\ --column\ --vimgrep
endif


" General colors
if has('gui_running') || has('nvim') || $TERM_PROGRAM == 'iTerm.app'
    hi Normal 		guifg=#586e75 guibg=#fdf6e3
else
    " Set the terminal default background and foreground colors, thereby
    " improving performance by not needing to set these colors on empty cells.
"   hi Normal guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE
"   let &t_ti = &t_ti . "\033]10;#586e75\007\033]11;#fdf6e3\007"
"   let &t_te = &t_te . "\033]1\007\033]1\007"
endif
